-- 코드를 작성해주세요
SELECT SUM(B.SCORE) SCORE, A.EMP_NO, A.EMP_NAME, A.POSITION, A.EMAIL 
FROM HR_EMPLOYEES A
JOIN HR_GRADE B ON A.EMP_NO = B.EMP_NO
GROUP BY A.EMP_NO
HAVING SCORE = (
    SELECT MAX(TOTAL_SCORE)
    FROM (
        SELECT SUM(SCORE) AS TOTAL_SCORE
        FROM HR_GRADE
        GROUP BY EMP_NO
    ) TMP
);
